services:

  scrapper:
    build:
      context: ./scrapper
      dockerfile: Dockerfile.scrapper
    container_name: scrapper
    volumes:
      - ./scrapper/app:/app
    environment:
      - WEBHDFS_URL=http://nn:9870
      - HDFS_USER=hadoop
    networks:
      - hadoop_net

  spark:
    build:
      context: .
      dockerfile: Dockerfile.spark
    container_name: spark
    hostname: spark
    networks:
      - hadoop_net
    volumes:
      - ./config/core-site.xml:/opt/spark/conf/core-site.xml
      - ./config/hdfs-site.xml:/opt/spark/conf/hdfs-site.xml
      - ./jobs:/jobs
      - ./scripts:/scripts
    ports:
      - "4040:4040"
      - "8080:8080"
    environment:
      - CAT_API_KEY=${CAT_API_KEY}

  nn:
    build:
      context: .
      dockerfile: Dockerfile.hadoop
    container_name: nn
    hostname: nn
    networks:
      - hadoop_net
    volumes:
      - ./hdfs/nn:/opt/hadoop/namenode
      - ./files:/home/hadoop/files
    ports:
      - "9870:9870"
      - "9000:9000"
      - "8088:8088"

  dn1:
    build:
      context: .
      dockerfile: Dockerfile.hadoop
    container_name: dn1
    hostname: dn1
    networks:
      - hadoop_net
    volumes:
      - ./hdfs/dn1:/opt/hadoop/datanode

  dn2:
    build:
      context: .
      dockerfile: Dockerfile.hadoop
    container_name: dn2
    hostname: dn2
    networks:
      - hadoop_net
    volumes:
      - ./hdfs/dn2:/opt/hadoop/datanode

  dn3:
    build:
      context: .
      dockerfile: Dockerfile.hadoop
    container_name: dn3
    hostname: dn3
    networks:
      - hadoop_net
    volumes:
      - ./hdfs/dn3:/opt/hadoop/datanode

networks:
  hadoop_net:
    driver: bridge
