services:
  spark:
    build:
      context: .
      dockerfile: Dockerfile.spark
    container_name: spark
    hostname: spark
    networks:
      - hadoop_net
    volumes:
      - ./config/core-site.xml:/opt/spark/conf/core-site.xml
      - ./config/hdfs-site.xml:/opt/spark/conf/hdfs-site.xml
      - ./jobs:/jobs
      - ./scraper:/scraper
    environment:
    - WEBHDFS_URL=http://nn:9870
    - HDFS_USER=hadoop
    - CAT_API_KEY=${CAT_API_KEY}
    - NLM_API_KEY=${NLM_API_KEY}
    ports:
      - "4040:4040"
      - "8080:8080"
      
  nn:
    build:
      context: .
      dockerfile: Dockerfile.hadoop
    container_name: nn
    hostname: nn
    networks:
      - hadoop_net
    volumes:
      - ./hdfs/nn:/opt/hadoop/namenode
    ports:
      - "9870:9870"
      - "9000:9000"
      - "8088:8088"

  dn1:
    build:
      context: .
      dockerfile: Dockerfile.hadoop
    container_name: dn1
    hostname: dn1
    networks:
      - hadoop_net
    volumes:
      - ./hdfs/dn1:/opt/hadoop/datanode

  dn2:
    build:
      context: .
      dockerfile: Dockerfile.hadoop
    container_name: dn2
    hostname: dn2
    networks:
      - hadoop_net
    volumes:
      - ./hdfs/dn2:/opt/hadoop/datanode

  dn3:
    build:
      context: .
      dockerfile: Dockerfile.hadoop
    container_name: dn3
    hostname: dn3
    networks:
      - hadoop_net
    volumes:
      - ./hdfs/dn3:/opt/hadoop/datanode

  postgres:
    image: postgres:16
    container_name: postgres
    hostname: postgres
    networks:
      - hadoop_net
    environment:
      POSTGRES_DB: cats_knowledge
      POSTGRES_USER: cats
      POSTGRES_PASSWORD: cats
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    hostname: pgadmin
    networks:
      - hadoop_net
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  streamlit:
    image: python:3.11-slim
    container_name: streamlit
    working_dir: /app
    volumes:
      - ./search_app:/app
    ports:
      - "8501:8501"
    networks:
      - hadoop_net
    command: >
      bash -c "pip install streamlit psycopg2-binary pandas &&
                python3 -m streamlit run app.py --server.address=0.0.0.0"
    depends_on:
      - postgres

networks:
  hadoop_net:
    driver: bridge

volumes:
  postgres_data:
