FROM python:3.9-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir \
    scrapy \
    requests \
    beautifulsoup4 \
    praw \
    biopython \
    scrapy-user-agents \
    hdfs \                     
    PyYAML

CMD ["scrapy", "shell"]