FROM python:3.14-slim

WORKDIR /app

RUN adduser scrapper \
    && echo "scrapper:scrapper" | chpasswd

RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir \
    requests beautifulsoup4 \
    praw biopython scrapy \
    hdfs PyYAML wikipedia-api \
    scrapy-user-agents  

CMD ["sleep", "infinity"]